### ISSUE TITLE
notepad++ 7.3.3 64bit

### ISSUE THREAD

**Issue by trueliarx** [phdesign/NppToolBucket#15]
are you going to release a dll plugin that works with notepad++ 7.3.3 64bit?
thank you

**Comment by jay** [comment]
You can build it if you have Visual Studio, just change `Build > Platform Target` to x64. Attached is a debug build of v1.7 x64 built with Visual Studio 2010. [NppToolBucket x64 v1.7.zip](https://github.com/phdesign/NppToolBucket/files/960754/NppToolBucket.x64.v1.7.zip)

**Comment by phdesign** [comment]
Thanks for raising this, I realise I've been a bit slack in providing updates. I'll get a build for x64 done asap

**Comment by trueliarx** [comment]
No problem. I compiled it as kindly suggested. Thank  you for your plugin. I really appreciate it!

**Comment by phdesign** [comment]
So it turns out I don't have a copy of VS2010 anymore and I can't build the current solution in VS2015 without upgrading the plugin template. I'll work on upgrading the plugin to the latest template here (https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net/releases), in the meantime @trueliarx are you able to send me the x64 binary and I'll upload it to the plugin page?

**Comment by chcg** [comment]
See PR #16, fix for using with VS2015 and minimal set of changes from https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net to work under x64 for n++.

Under https://ci.appveyor.com/project/chcg/npptoolbucket/build/1.7.3/job/g9vii4gomby4swen/artifacts you will also find builded artifacts with VS2015.

**Comment by phdesign** [comment]
Thanks to @chcg I've built a 64-bit version, available here: http://phdesign.com.au/npptoolbucket/
